-- STORED PROCEDURE
-- EMPLOYEES에서 사용자 이름을 패턴으로 검색한 뒤 해당되는 사용자 정보를 출력

SELECT * FROM EMPLOYEES WHERE UPPER(FIRST_NAME) LIKE UPPER('%p%');


CREATE OR REPLACE PROCEDURE EMP_PROC
IS
    --문자 변수 선언
    VWORD VARCHAR2(1);
    VEMP_ROWTYPE EMPLOYEES%ROWTYPE;
    CURSOR CURSOR_NAME(VNAME VARCHAR2)
    IS
    SELECT * FROM EMPLOYEES WHERE UPPER(FIRST_NAME) LIKE UPPER('%' || VNAME || '%');
BEGIN
    --임의의 문자 생성
    VWORD := DBMS_RANDOM.STRING('U', 1);
    
    FOR VEMP_ROWTYPE IN CURSOR_NAME(VWORD) LOOP
        DBMS_OUTPUT.PUT_LINE(VEMP_ROWTYPE.FIRST_NAME || ' / ' || VEMP_ROWTYPE.SALARY);
    END LOOP;
END;
/

EXECUTE EMP_PROC;