-- 자바에서 CallableStatement test
CREATE TABLE EMP1
AS
SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID, SALARY FROM EMPLOYEES;

SELECT * FROM EMP1;

-- 부서별로 해당되는 부서만 인상률이 적용되는 프로시저
CREATE OR REPLACE PROCEDURE BOOKS_PROCEDURE(
    VID IN BOOKS.ID%TYPE, VPRICE IN BOOKS.PRICE%TYPE)
IS
BEGIN
    UPDATE BOOKS 
    SET PRICE= PRICE + VPRICE
    WHERE ID = VID;
    COMMIT;
END;
/

SELECT * FROM BOOKS;

EXECUTE BOOKS_PROCEDURE(1, 10000);

SELECT * FROM EMP1 ORDER BY DEPARTMENT_ID;