--학과테이블 생성
CREATE TABLE SUBJECT01(
    no NUMBER(10),--pk 
    subnum CHAR(2)NOT NULL,--학과번호
    name VARCHAR2(50)NOT NULL --학과명
    
);
ALTER TABLE SUBJECT01 ADD CONSTRAINT SUBJECT01_no_PK PRIMARY KEY(no);
SELECT * FROM SUBJECT01;

--학생테이블 생성
CREATE TABLE STUDENT01(
    no NUMBER(10),--pk
    stunum CHAR(8) NOT NULL, --학번
    name VARCHAR2(50)NOT NULL,--이름
    id VARCHAR2(20)NOT NULL,--아이디
    pwd VARCHAR2(20)NOT NULL,--비밀번호
    subnum CHAR(2),--학과번호----------------------FK
    jumin CHAR(13)NOT NULL,--주민등록번호
    phone VARCHAR2 (15)NOT NULL, --핸드폰번호
    address VARCHAR2 (100)NOT NULL,--주소
    email VARCHAR2(50)NOT NULL,--이메일
    stu_date DATE DEFAULT SYSDATE--등록일자
);

ALTER TABLE STUDENT01 ADD CONSTRAINT STUDENT01_no_PK PRIMARY KEY(no);
ALTER TABLE STUDENT01 ADD CONSTRAINT STUDENT01_subnum_FK FOREIGN KEY(subnum) REFERENCES SUBJECT01(subnum);
SELECT * FROM STUDENT01;

--과목테이블 생성
CREATE TABLE LESSON01(
    no NUMBER(10),--pk
    lnum CHAR(1)NOT NULL, --과목번호
    name VARCHAR2(50)NOT NULL--과목명
);

ALTER TABLE LESSON01 ADD CONSTRAINT LESSON01_no_PK PRIMARY KEY(no);
SELECT * FROM LESSON01;

--수강테이블 생성
CREATE TABLE TRAINEE01(
    no NUMBER(10),--pk 
    stunum CHAR(8) NOT NULL, --학번--------FK 
    lnum CHAR(1)NOT NULL, --과목번호 -------FK
    section VARCHAR(20) NOT NULL,--과목구분
    train_date DATE DEFAULT SYSDATE--등록일자
);

ALTER TABLE TRAINEE01 ADD CONSTRAINT TRAINEE01_no_PK PRIMARY KEY(no);
ALTER TABLE TRAINEE01 ADD CONSTRAINT TRAINEE01_stunum_FK FOREIGN KEY(stunum) REFERENCES STUDENT01(stunum);
ALTER TABLE TRAINEE01 ADD CONSTRAINT TRAINEE01_lnum_FK FOREIGN KEY(lnum) REFERENCES LESSON01(lnum);
SELECT * FROM TRAINEE01;