-- 고객 정보 테이블
CREATE TABLE CUSTOMER(
    CODE CHAR(2),
    ID VARCHAR2(15) NOT NULL,
    PWD VARCHAR2(15) NOT NULL,
    NAME VARCHAR2(6) NOT NULL,
    ADDRESS VARCHAR2(50) NOT NULL,
    PHONE CHAR(13) NOT NULL
);
ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_CODE_PK PRIMARY KEY(CODE);
ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_ID_UK UNIQUE(ID);
ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_PHONE_UK UNIQUE(PHONE);

-- 상품 정보 테이블
CREATE TABLE PRODUCT (
    CODE CHAR(2),
    NAME VARCHAR2(10) NOT NULL ,
    PRICE NUMBER(7) NOT NULL,
    REMAIN NUMBER(3) NOT NULL
);
ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_CODE_PK PRIMARY KEY(CODE);
ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_NAME_UK UNIQUE(NAME);
