--PL/SQL
--내용을 화면에 출력하기
DECLARE
    --테이블타입정의
    TYPE FIRST_NAME_ARRAY_TYPE IS TABLE OF EMPLOYEES.FIRST_NAME%TYPE INDEX BY BINARY_INTEGER;
    TYPE JOB_ID_ARRAY_TYPE IS TABLE OF EMPLOYEES.JOB_ID%TYPE INDEX BY BINARY_INTEGER;
    TYPE EMPLOYEE_ID_ARRAY_TYPE IS TABLE OF EMPLOYEES.EMPLOYEE_ID%TYPE INDEX BY BINARY_INTEGER;
    --배열타입변수선언
    FIRST_NAME_ARRAY FIRST_NAME_ARRAY_TYPE;
    JOB_ID_ARRAY JOB_ID_ARRAY_TYPE;
    EMPLOYEE_ID_ARRAY EMPLOYEE_ID_ARRAY_TYPE;
    ROW_ARRAY EMPLOYEES%ROWTYPE;
    I BINARY_INTEGER := 0;
    J BINARY_INTEGER;
BEGIN   
    --PLSQL FOR문
    FOR ROW_ARRAY IN (SELECT * FROM EMPLOYEES)LOOP
        I := I + 1;
        FIRST_NAME_ARRAY(I) := ROW_ARRAY.FIRST_NAME;
        JOB_ID_ARRAY(I) := ROW_ARRAY.JOB_ID;
        EMPLOYEE_ID_ARRAY(I) := ROW_ARRAY.EMPLOYEE_ID;
   END LOOP;     
   -- 향상된 for문을 이용해서 칼럼 배열값에 저장된 값을 가져와서 출력
   FOR J IN 1..I LOOP
       DBMS_OUTPUT.PUT_LINE(FIRST_NAME_ARRAY(J) || ' / ' || JOB_ID_ARRAY(J)|| ' / ' || EMPLOYEE_ID_ARRAY(J));
    
   END LOOP;
   
   
END;
/
