-- INSERT INTO 테이블명(컬럼명,,) VALUES (컬럼값, ,,)
-- DELETE FROM 테이블명 WHERE
-- UPDATE 테이블명 SET WHERE

CREATE TABLE INSERT_TEST(
    NO1 NUMBER,
    NO2 NUMBER,
    NO3 NUMBER
);

DESC INSERT_TEST;
INSERT INTO INSERT_TEST VALUES(1,2,3);
SELECT * FROM INSERT_TEST;
RENAME INSERT_TEST TO IT;
DESC IT;

INSERT INTO IT VALUES(1,2,3);
INSERT INTO IT VALUES(1,2,NULL);
INSERT INTO IT(NO1,NO2) VALUES(11,22);

DELETE FROM IT WHERE NO3 IS NULL;
ALTER TABLE IT MODIFY NO3 NUMBER NOT NULL;
SELECT * FROM IT;

CREATE TABLE DEPT
AS 
SELECT DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID FROM DEPARTMENTS;
SELECT * FROM DEPT;
DELETE FROM DEPT;
TRUNCATE TABLE DEPT;
ROLLBACK;

INSERT INTO DEPT SELECT DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID FROM DEPARTMENTS;