-- 순위함수 RANK(), DENSE_RANK(), ROWNUM
-- ROWNUM 이용하여 순위 구하기(공동순위가 없음: 게시판, 공지사항, 자료실)
DROP TABLE EMP02;
CREATE TABLE EMP02
AS
SELECT * FROM EMPLOYEES WHERE 1 = 1;
SELECT * FROM EMP02;
SELECT ROWNUM, FIRST_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY DESC;
SELECT ROWNUM, FIRST_NAME, SALARY FROM EMPLOYEES;
SELECT ROWNUM, FIRST_NAME, SALARY FROM (SELECT ROWNUM, FIRST_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY DESC);

-- 공동 순위 구하는 방법
-- RANK()
SELECT RANK() OVER(ORDER BY SALARY DESC) AS RANK, FIRST_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY DESC;
SELECT RANK() OVER(ORDER BY SALARY DESC) AS RANK, FIRST_NAME, SALARY 
FROM (SELECT ROWNUM, FIRST_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY DESC) ORDER BY SALARY DESC;
-- DENSE_RANK()
SELECT ROWNUM, DENSE_RANK() OVER(ORDER BY SALARY DESC) AS DENSE_RANK, FIRST_NAME, SALARY 
FROM EMPLOYEES ORDER BY SALARY DESC;
SELECT ROWNUM, DENSE_RANK() OVER(ORDER BY SALARY DESC) AS DENSE_RANK, FIRST_NAME, SALARY 
FROM (SELECT ROWNUM, FIRST_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY DESC) ORDER BY SALARY DESC;

SELECT ROWNUM, DENSE_RANK() OVER(ORDER BY SALARY DESC) AS RANK, FIRST_NAME, SALARY 
FROM (SELECT ROWNUM, FIRST_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY DESC) ORDER BY SALARY DESC;

-- 중복순위 없애기
SELECT  RANK() OVER(ORDER BY SALARY DESC, COMMISSION_PCT DESC) AS RANK
, FIRST_NAME, SALARY, COMMISSION_PCT, DEPARTMENT_ID 
FROM EMPLOYEES ORDER BY SALARY DESC;