SELECT * FROM STUDENT;
DROP TABLE STUDENT;
CREATE TABLE STUDENT(
    STUNUM NUMBER(4),
    NAME VARCHAR2(20) NOT NULL,
    KOR NUMBER(4) NOT NULL,
    ENG NUMBER(4)NOT NULL,
    MAT NUMBER(4)
);

ALTER TABLE STUDENT ADD CONSTRAINT STUDENT_STUNUM_PK PRIMARY KEY(STUNUM);

CREATE SEQUENCE STUDENT_STUNUM_SEQ
START WITH 1
INCREMENT BY 1;

INSERT INTO STUDENT VALUES(STUDENT_STUNUM_SEQ.nextval, 'Operating System Concepts', 'Wiley', '2003',30700);