-- 학과 테이블 (01-컴퓨터학과 / 02-교육학과 / 03-신문방송학과 / 04-인터넷비즈니스과 / 05-기술경영과)
CREATE TABLE SUBJECT(
    NO NUMBER ,                 -- pk,seq
    NUM VARCHAR2(2) NOT NULL,   -- 학과번호
    NAME VARCHAR2(24) NOT NULL  -- 학과이름
);

ALTER TABLE SUBJECT ADD CONSTRAINT SUBJECT_NO_PK PRIMARY KEY(NO);
ALTER TABLE SUBJECT ADD CONSTRAINT SUBJECT_NUM_UK UNIQUE(NUM);

CREATE SEQUENCE SUBJECT_SEQ
START WITH 1
INCREMENT BY 1;

-- 학생 테이블
CREATE TABLE STUDENT(
    NO NUMBER ,                    -- pk,seq
    NUM VARCHAR2(8) NOT NULL,      -- 학번
    NAME VARCHAR2(12) NOT NULL,    -- 이름
    ID VARCHAR2(12) NOT NULL,      -- 아이디
    PASSWD VARCHAR2(12) NOT NULL,  -- 패스워드
    S_NUM VARCHAR2(2) NOT NULL,    -- fk,학과번호
    BIRTHDAY VARCHAR2(8) NOT NULL, -- 생년월일
    PHONE VARCHAR2(15) NOT NULL,   -- 전화번호
    ADDRESS VARCHAR2(80) NOT NULL, -- 주소
    EMAIL VARCHAR2(40) NOT NULL,   -- 이메일
    SDATE DATE DEFAULT SYSDATE     -- 등록일
);

ALTER TABLE STUDENT ADD CONSTRAINT STUDENT_NO_PK PRIMARY KEY(NO);
ALTER TABLE STUDENT ADD CONSTRAINT STUDENT_ID_UK UNIQUE(ID);
ALTER TABLE STUDENT ADD CONSTRAINT STUDENT_NUM_UK UNIQUE(NUM);
-- 제약조건 삭제
ALTER TABLE STUDENT DROP CONSTRAINT STUDENT_SUBJECT_NUM_FK;

ALTER TABLE STUDENT ADD CONSTRAINT STUDENT_SUBJECT_NUM_FK FOREIGN KEY(S_NUM) 
    REFERENCES SUBJECT(NUM) ON DELETE SET NULL;

CREATE SEQUENCE STUDENT_SEQ
START WITH 1
INCREMENT BY 1;

-- 학과테이블과 학생테이블 INNER JOIN
SELECT STU.NO, STU.NUM, STU.NAME, STU.ID, PASSWD, STU.S_NUM, SUB.NAME AS SUBJECT_NAME, BIRTHDAY,PHONE,ADDRESS, EMAIL, SDATE 
FROM STUDENT STU INNER JOIN SUBJECT SUB ON STU.S_NUM = SUB.NUM;

-- 과목 테이블
CREATE TABLE LESSON(
    NO NUMBER ,                 -- pk,seq
    ABBRE VARCHAR2(2) NOT NULL, -- 과목요약
    NAME VARCHAR2(20) NOT NULL  -- 과목이름
);

ALTER TABLE LESSON ADD CONSTRAINT LESSON_NO_PK PRIMARY KEY(NO);
ALTER TABLE LESSON ADD CONSTRAINT LESSON_ABBRE_UK UNIQUE(ABBRE);

CREATE SEQUENCE LESSON_SEQ
START WITH 1
INCREMENT BY 1;

-- 수강신청 테이블
CREATE TABLE TRAINEE(
    NO NUMBER ,                         -- pk,seq
    S_NUM VARCHAR2(8) NOT NULL,         -- fk,학생번호
    ABBRE VARCHAR2(2) NOT NULL,         -- fk,과목요약
    SECTION VARCHAR2(20) NOT NULL,      -- 전공,부전공,교양
    TDATE DATE DEFAULT SYSDATE          -- 수강신청일
);

ALTER TABLE TRAINEE ADD CONSTRAINT TRAINEE_NO_PK PRIMARY KEY(NO);
ALTER TABLE TRAINEE ADD CONSTRAINT TRAINEE_STUDENT_NUM_FK FOREIGN KEY(S_NUM) 
    REFERENCES STUDENT(NUM) ON DELETE SET NULL;
ALTER TABLE TRAINEE ADD CONSTRAINT TRAINEE_LESSON_ABBRE_FK FOREIGN KEY(ABBRE) 
    REFERENCES LESSON(ABBRE) ON DELETE SET NULL;

CREATE SEQUENCE TRAINEE_SEQ
START WITH 1
INCREMENT BY 1;

