CREATE TABLE EMP01(
    no NUMBER(4),
    name VARCHAR(20) NOT NULL,
    salary NUMBER(10,2) DEFAULT 1000.0,
    CONSTRAINT EMP01_no_PK PRIMARY KEY(no),
    CONSTRAINT EMP01_no_UK UNIQUE(name)
);

--테이블 정보 구하기
SELECT * FROM tab;
--테이블 삭제하기
DROP TABLE EMP01;
-- 휴지통보기
SELECT * FROM RECYCLEBIN;
--테이블 복사
DESC EMPLOYEES;
SELECT COUNT(*) FROM EMPLOYEES;
CREATE TABLE EMPLE02
as
SELECT * FROM EMPLOYEES;
DESC EMPLE02;
SELECT COUNT(*) FROM EMPLE02;
-- 제약조건 걸기 
ALTER TABLE EMPLE02 ADD CONSTRAINT EMPLE02_ID_PK PRIMARY KEY(EMPLOYEE_ID);
ALTER TABLE EMPLE02 ADD CONSTRAINT EMPLE02_EMAIL_UK UNIQUE(EMAIL);
-- 제약조건 삭제하기
ALTER TABLE EMPLE02 DROP CONSTRAINT EMPLE02_EMAIL_UK;
-- 제약조건 정보 검색
SELECT * FROM user_constraints;
SELECT * FROM user_constraints WHERE TABLE_NAME = 'EMPLE02';

-- 컬럼추가 emp01
ALTER TABLE EMP01 ADD JOB VARCHAR2(10) NOT NULL;
DESC EMP01;
-- 컬럼제거 emp01
ALTER TABLE EMP01 DROP COLUMN JOB;
-- 컬럼변경 emp01
ALTER TABLE EMP01 MODIFY JOB NUMBER(10) DEFAULT 0;
-- 컬럼이름변경
ALTER TABLE EMP01 RENAME COLUMN JOB TO JOB2;
ALTER TABLE EMP01 RENAME COLUMN JOB2 TO JOB;

-- 테이블명을 변경 EMP01 => EMP02
RENAME EMP01 TO EMP02;
SELECT * FROM TAB;

DESC EMPLE01;


CREATE TABLE EMPLE01(
    code VARCHAR(7),
    name VARCHAR(10) NOT NULL,
    gender VARCHAR(1)NOT NULL,
    birth NUMBER(8) NOT NULL,
    no NUMBER(16),
    email VARCHAR(30),
    point NUMBER(10)
    
);

ALTER TABLE EMPLE01 ADD CONSTRAINT EMPLE01_code_PK PRIMARY KEY(code);
ALTER TABLE EMPLE01 ADD CONSTRAINT EMPLE01_gender_CK CHECK(gender IN('M','W'));
ALTER TABLE EMPLE01 ADD CONSTRAINT EMPLE01_EMAIL_UK UNIQUE(EMAIL);


DESC EMPLE01;

CREATE TABLE CUSTOMER(
    code CHAR(7),
    name VARCHAR2(10) NOT NULL,
    gender CHAR(1)NOT NULL,
    birth CHAR(8) NOT NULL,
    no VARCHAR2(16),
    email VARCHAR2(30),
    point NUMBER(10) DEFAULT 0
    
);

ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_code_PK PRIMARY KEY(code);
ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_gender_CK CHECK(gender IN('M','W'));
ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_EMAIL_UK UNIQUE(EMAIL);

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'CUSTOMER';


