--PL/SQL
DECLARE
    VDEPARTMENTS DEPARTMENTS%ROWTYPE;

BEGIN
    FOR I IN 1..9 LOOP
    SELECT * INTO VDEPARTMENTS FROM DEPARTMENTS WHERE DEPARTMENT_ID = I * 10;
    DBMS_OUTPUT.PUT_LINE(VDEPARTMENTS.DEPARTMENT_ID || '/ ' ||VDEPARTMENTS.DEPARTMENT_NAME);
    
    END LOOP;

END;
/

