SELECT * FROM STUDENT;
DROP TABLE STUDENT;
CREATE TABLE STUDENT(
    STUNUM NUMBER(4),
    NAME VARCHAR2(20) NOT NULL,
    KOR NUMBER(4) NOT NULL,
    ENG NUMBER(4)NOT NULL,
    MAT NUMBER(4)NOT NULL
);

ALTER TABLE STUDENT ADD CONSTRAINT STUDENT_STUNUM_PK PRIMARY KEY(STUNUM);

CREATE SEQUENCE STUDENT_STUNUM_SEQ
START WITH 1
INCREMENT BY 1;

INSERT INTO STUDENT VALUES(STUDENT_STUNUM_SEQ.NEXTVAL, '홍길동', '90', '70', '70');
INSERT INTO STUDENT VALUES(STUDENT_STUNUM_SEQ.NEXTVAL, '김길동', '80', '25', '66');
INSERT INTO STUDENT VALUES(STUDENT_STUNUM_SEQ.NEXTVAL, '이길동', '100', '75', '89');
COMMIT;


SELECT * FROM STUDENT;