-- 회원 테이블 생성
CREATE TABLE CUSTOMER (
    CODE CHAR(5),                   -- 고객 코드 (고유 식별자)
    NAME VARCHAR2(50) NOT NULL,     -- 고객 이름
    ID VARCHAR2(15) NOT NULL,       -- 아이디 (고유, 중복 불가)
    PWD VARCHAR2(15) NOT NULL,      -- 비밀번호
    BIRTH VARCHAR2(8) NOT NULL,     -- 생년월일
    PHONE VARCHAR2(15) NOT NULL,    -- 전화번호
    ADDRESS VARCHAR2(100)NOT NULL,  -- 주소
    EMAIL VARCHAR2(40) NOT NULL,    -- 이메일
    CDATE DATE DEFAULT SYSDATE      -- 가입일자
);

ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_CODE_PK PRIMARY KEY(CODE);
ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_ID_UK UNIQUE(ID);

SELECT * FROM CUSTOMER;

-- 회원코드 시퀀스 생성
CREATE SEQUENCE CUSTOMER_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 회원코드 트리거 생성
CREATE OR REPLACE TRIGGER CUSTOMER_TRG
BEFORE INSERT ON CUSTOMER
FOR EACH ROW
BEGIN
    :NEW.CODE := LPAD(CUSTOMER_SEQ.NEXTVAL, 5, '0');
END;
/

-- 상품 테이블 생성
CREATE TABLE PRODUCT (
    CODE CHAR(5) PRIMARY KEY,          -- 상품 코드 (고유 식별자)
    NAME VARCHAR2(50) NOT NULL UNIQUE, -- 상품명 (고유, 중복 불가)
    PRICE NUMBER(10, 2) NOT NULL,      -- 가격
    STOCK NUMBER(5) NOT NULL           -- 재고 수량
);

-- 상품코드 시퀀스 생성
CREATE SEQUENCE PRODUCT_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 상품코드 트리거 생성
CREATE OR REPLACE TRIGGER PRODUCT_TRG
BEFORE INSERT ON PRODUCT
FOR EACH ROW
BEGIN
    :NEW.CODE := LPAD(PRODUCT_SEQ.NEXTVAL, 5, '0');
END;
/

-- 주문 테이블 생성
CREATE TABLE ORDERS (
    CODE CHAR(5),                     -- 주문 코드 (고유 식별자)
    CUST_CODE CHAR(5) NOT NULL,       -- 고객 코드 (외래 키)
    PRO_NAME VARCHAR2(50) NOT NULL,   -- 상품명 (외래 키로 변경)
    BUY NUMBER(5) NOT NULL,           -- 주문 수량
    TOTAL NUMBER(10, 2),              -- 총 금액
    STATUS VARCHAR2(20) NOT NULL      -- 배송 상태 (예: "주문 접수", "배송 중", "배송 완료")
);

ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_CUSTOMER_CODE_FK FOREIGN KEY(CUST_CODE)
    REFERENCES CUSTOMER(CODE) ON DELETE CASCADE;
ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_PRODUCT_NAME_FK FOREIGN KEY(PRO_NAME) 
    REFERENCES PRODUCT(NAME) ON DELETE SET NULL;
    
    
-- 주문코드 시퀀스 생성
CREATE SEQUENCE ORDERS_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 주문코드 트리거 생성
CREATE OR REPLACE TRIGGER ORDERS_CODE_TRG
BEFORE INSERT ON ORDERS
FOR EACH ROW
BEGIN
    :NEW.CODE := LPAD(ORDERS_SEQ.NEXTVAL, 5, '0');
END;
/


-- 주문 테이블에 대한 트리거 생성 (총 금액 자동 계산)
CREATE OR REPLACE TRIGGER ORDERS_TRG
BEFORE INSERT OR UPDATE ON ORDERS
FOR EACH ROW
DECLARE
    V_PRICE NUMBER(10, 2);
BEGIN
    -- 상품 가격 조회
    SELECT PRICE INTO V_PRICE FROM PRODUCT WHERE NAME = :NEW.PRO_NAME;
    -- 총 금액 계산
    :NEW.TOTAL := V_PRICE * :NEW.BUY;
END;
/
